/*
 * generated by Xtext 2.15.0
 */
package trichterwolke.init


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class InitStandaloneSetup extends InitStandaloneSetupGenerated {

	def static void doSetup() {
		new InitStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
