/*
 * generated by Xtext 2.15.0
 */
package trichterwolke.init.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import trichterwolke.init.InitRuntimeModule
import trichterwolke.init.InitStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class InitIdeSetup extends InitStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new InitRuntimeModule, new InitIdeModule))
	}
	
}
